use_frameworks!

install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true

platform :ios, '9.0'

target 'KLCache_Example' do
  pod 'KLCache', :path => '../'

  target 'KLCache_Tests' do
    inherit! :search_paths

    
  end
end
